admin_panel/urls.py
from django.urls import path

from admin_panel.views import hello_world, SeoBlockListView, SeoBlockCreateView, SeoBlockUpdateView, SeoBlockDeleteView, \
    MainPageListView, MainPageCreateView, MainPageUpdateView, MainPageDeleteView, ContactPageListView, \
    ContactPageCreateView, ContactPageUpdateView, ContactPageDeleteView

urlpatterns = [
    path("", hello_world, name="hello_world"),

    path("seo_block/", SeoBlockListView.as_view(), name="seo_block_list"),
    path("seo_block/create/", SeoBlockCreateView.as_view(), name="seo_block_create"),
    path("seo_block/update/<int:pk>/", SeoBlockUpdateView.as_view(), name="seo_block_update"),
    path("seo_block/delete/<int:pk>/", SeoBlockDeleteView.as_view(), name="seo_block_delete"),

    path("main/", MainPageListView.as_view(), name="main_page_list"),
    path("main/create/", MainPageCreateView.as_view(), name="main_page_create"),
    path("main/update/<int:pk>/", MainPageUpdateView.as_view(), name="main_page_update"),
    path("main/delete/<int:pk>/", MainPageDeleteView.as_view(), name="main_page_delete"),

    path("contact_page/", ContactPageListView.as_view(), name="contact_page_list"),
    path("contact_page/create/", ContactPageCreateView.as_view(), name="contact_page_create"),
    path("contact_page/update/<int:pk>/", ContactPageUpdateView.as_view(), name="contact_page_update"),
    path("contact_page/delete/<int:pk>/", ContactPageDeleteView.as_view(), name="contact_page_delete"),

]

app_name = "admin_panel"

cinema_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path("admin/", admin.site.urls),
  path("admin_panel/", include("admin_panel.urls", namespace="admin_panel")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/models/banner.py
from django.db import models
from admin_panel.models.image import ImageTitle


class BackgroundBanner(models.Model):
    class BackgroundType(models.TextChoices):
        PHOTO = "photo", "Фото на фоні"
        COLOR = "color", "Просто фон"

    type = models.CharField(
        max_length=20,
        choices=BackgroundType.choices,
        default=BackgroundType.COLOR,
        verbose_name="Тип фону"
    )
    image = models.ImageField(
        upload_to="banners/backgrounds/",
        null=True,
        blank=True,
        verbose_name="Фонове зображення"
    )

    def __str__(self):
        return f"{self.get_type_display()} ({self.image.name if self.image else 'Без зображення'})"


class Banner(models.Model):
    class BannerType(models.TextChoices):
        MAIN = "main", "Головний"
        NEWS = "news", "Новини"

    type = models.CharField(
        max_length=20,
        choices=BannerType.choices,
        default=BannerType.MAIN,
        verbose_name="Тип банера"
    )
    collection = models.ForeignKey(
        ImageTitle,
        on_delete=models.CASCADE,
        related_name="banners",
        null=True,
        verbose_name="Колекція зображень"
    )
    is_published = models.BooleanField(default=False, verbose_name="Опубліковано")
    rotation_speed = models.PositiveIntegerField(
        null=True,
        blank=True,
        default=0,
        verbose_name="Швидкість ротації (сек)"
    )

    def __str__(self):
        return f"{self.get_type_display()} - {self.collection.name if self.collection else 'Без колекції'}"

admin_panel/models/cinema_hall.py
from django.db import models
from django.utils import timezone

from admin_panel.models.image import ImageTitle
from admin_panel.models.seo import SeoBlock


class Cinema(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    condition = models.TextField(blank=True)
    logo_cinema = models.ImageField(upload_to="cinema_logos/", null=True, blank=True)
    banner_cinema = models.ImageField(upload_to="cinema_banners/", null=True, blank=True)
    collection = models.ForeignKey(
        ImageTitle,
        on_delete=models.CASCADE,
        related_name="cinemas",
        blank=True,
        null=True,
    )
    seo_cinema = models.ForeignKey(
        SeoBlock,
        on_delete=models.CASCADE,
        related_name="cinemas",
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["title"]
        verbose_name = "Cinema"
        verbose_name_plural = "Cinemas"


class Hall(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    logo_hall = models.ImageField(upload_to="hall_logos/", null=True, blank=True)
    banner_hall = models.ImageField(upload_to="hall_banners/", null=True, blank=True)
    collection = models.ForeignKey(
        ImageTitle,
        on_delete=models.CASCADE,
        related_name="halls",
        blank=True,
        null=True,
    )
    seo_hall = models.ForeignKey(
        SeoBlock,
        on_delete=models.CASCADE,
        related_name="halls",
        blank=True,
        null=True,
    )
    cinema = models.ForeignKey(
        Cinema,
        on_delete=models.CASCADE,
        related_name="halls",
    )
    published_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["title"]
        verbose_name = "Hall"
        verbose_name_plural = "Halls"

admin_panel/models/contact.py
from django.db import models
from django.utils import timezone

from admin_panel.models.seo import SeoBlock


class ContactPage(models.Model):
    title = models.CharField(max_length=255)
    is_published = models.BooleanField(default=False)
    seo = models.ForeignKey(
        SeoBlock,
        on_delete=models.CASCADE,
        related_name="contact_pages"
    )
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-published_date']
        verbose_name = "Contact Page"
        verbose_name_plural = "Contact Pages"


class Contact(models.Model):
    title = models.CharField(max_length=255)
    address = models.TextField(blank=True, null=True)
    coordinates = models.URLField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    logo = models.ImageField(upload_to="contact_logos/", blank=True, null=True)
    page = models.ForeignKey(
        ContactPage,
        on_delete=models.CASCADE,
        related_name="contacts",
        null=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["title"]
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"

admin_panel/models/film.py
from django.db import models
from admin_panel.models.image import ImageTitle
from admin_panel.models.seo import SeoBlock


class Film(models.Model):
    class ShowType(models.IntegerChoices):
        POSTER = 0, "Poster"
        IN_WHILE = 1, "In While"

    class FormatType(models.TextChoices):
        TWO_D = "2D", "2D"
        THREE_D = "3D", "3D"
        IMAX = "IMAX", "IMAX"

    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    film_image = models.ImageField(upload_to="films/", null=True, blank=True)
    collection = models.ForeignKey(
        ImageTitle,
        on_delete=models.CASCADE,
        related_name="films",
        blank=True,
        null=True
    )
    link = models.URLField(blank=True, null=True)
    type_show = models.IntegerField(choices=ShowType.choices, default=ShowType.POSTER)
    seo_film = models.ForeignKey(
        SeoBlock,
        on_delete=models.CASCADE,
        related_name="films",
        blank=True,
        null=True
    )
    format_type = models.CharField(
        max_length=10,
        choices=FormatType.choices,
        default=FormatType.TWO_D
    )

    created_at = models.DateTimeField(auto_now_add=True)  # коли додано фільм
    updated_at = models.DateTimeField(auto_now=True)  # коли востаннє змінено

    def __str__(self):
        return self.title

    class Meta:
        db_table = "film"
        ordering = ["title"]
        verbose_name = "Film"
        verbose_name_plural = "Films"

admin_panel/models/main_page.py
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField

from admin_panel.models.image import ImageTitle
from admin_panel.models.seo import SeoBlock


class MainPage(models.Model):
    title = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    published_date = models.DateTimeField(default=timezone.now)
    phone_primary = PhoneNumberField()
    phone_secondary = PhoneNumberField()
    seo_description = models.TextField(blank=True, null=True)
    seo = models.ForeignKey(
        SeoBlock,
        on_delete=models.CASCADE,
        related_name="main_pages",
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-published_date"]
        verbose_name = "Main Page"
        verbose_name_plural = "Main Pages"


class SecondPage(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    is_published = models.BooleanField(default=True)
    image = models.ImageField(upload_to="second_page_images/", blank=True, null=True)
    collection = models.ForeignKey(
        ImageTitle,
        on_delete=models.CASCADE,
        related_name="second_pages",
    )
    seo = models.ForeignKey(
        SeoBlock,
        on_delete=models.CASCADE,
        related_name="second_pages",
    )
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-published_date"]
        verbose_name = "Second Page"
        verbose_name_plural = "Second Pages"

main/models.py
from django.db import models

# Create your models here.

admin_panel/forms/contact.py
from django import forms
from django.forms import modelformset_factory, inlineformset_factory

from admin_panel.models import ContactPage, Contact


class ContactForm(forms.ModelForm):
    model = Contact
    fields = ['title', 'address', 'coordinates', 'is_active', 'logo']


class ContactPageForm(forms.ModelForm):
    class Meta:
        model = ContactPage
        fields = '__all__'


ContactFormSet = inlineformset_factory(
    ContactPage,
    Contact,
    form=ContactForm,
    extra=1,
    can_delete=True,
    exclude=("page",)
)

admin_panel/forms/main_page.py
from django import forms

from admin_panel.models import MainPage


class MainPageForm(forms.ModelForm):
    class Meta:
        model = MainPage
        fields = "__all__"

admin_panel/forms/seo.py
from django import forms
from admin_panel.models.seo import SeoBlock

class SeoForm(forms.ModelForm):
    class Meta:
        model = SeoBlock
        fields = "__all__"

    # Додаткову логіку валідації можна прописувати тут
    def clean_url(self):
        url = self.cleaned_data.get('url')
        if not url.startswith("http"):
            raise forms.ValidationError("URL повинен починатися з http або https")
        return url

admin_panel/views/contact.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from admin_panel.models import ContactPage
from admin_panel.forms.contact import ContactPageForm, ContactFormSet


class ContactPageListView(generic.ListView):
    model = ContactPage
    context_object_name = "contact_list"
    template_name = "contact/contact_page_list.html"


class ContactPageCreateView(generic.CreateView):
    model = ContactPage
    form_class = ContactPageForm
    template_name = "contact/contact_page_form.html"
    success_url = reverse_lazy("admin_panel:contact_page_list")

    def dispatch(self, request, *args, **kwargs):
        if ContactPage.objects.exists():
            messages.warning(request, "The contact page has already been created. Creating a new one is prohibited.")
            return redirect('admin_panel:contact_page_list')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['contact_formset'] = ContactFormSet(self.request.POST, self.request.FILES, prefix='contacts')
        else:
            context['contact_formset'] = ContactFormSet(prefix='contacts')
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        contact_formset = context['contact_formset']
        if contact_formset.is_valid():
            self.object = form.save()
            contact_formset.instance = self.object
            contact_formset.save()
            return super().form_valid(form)
        return self.form_invalid(form)


class ContactPageUpdateView(generic.UpdateView):
    model = ContactPage
    form_class = ContactPageForm
    template_name = "contact/contact_page_form.html"
    success_url = reverse_lazy("admin_panel:contact_page_list")

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['contact_formset'] = ContactFormSet(
                self.request.POST,
                self.request.FILES,
                instance=self.object,
                prefix='contacts'
            )
        else:
            data['contact_formset'] = ContactFormSet(instance=self.object, prefix='contacts')
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        contact_formset = context['contact_formset']

        if contact_formset.is_valid():
            self.object = form.save()
            contact_formset.instance = self.object
            contact_formset.save()  # тут Django видалить ті, де DELETE=True
            return super().form_valid(form)
        return self.form_invalid(form)


class ContactPageDeleteView(generic.DeleteView):
    model = ContactPage
    context_object_name = "contact_page"
    template_name = "contact/contact_page_confirm_delete.html"
    success_url = reverse_lazy("admin_panel:contact_page_list")

admin_panel/views/image.py
from django.http import HttpResponse
from django.shortcuts import render


def hello_world(request):
    return render(request, "home.html")

admin_panel/views/main_page.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from admin_panel.models import MainPage
from admin_panel.forms.main_page import MainPageForm

class MainPageListView(generic.ListView):
    model = MainPage
    context_object_name = 'main_page_list'
    template_name = "main/main_page_list.html"

class MainPageCreateView(generic.CreateView):
    model = MainPage
    form_class = MainPageForm
    template_name = "main/main_page_form.html"
    success_url = reverse_lazy("admin_panel:main_page_list")


    def dispatch(self, request, *args, **kwargs):
        # Якщо вже є хоча б один MainPage – редіректимо на список
        if MainPage.objects.exists():
            messages.warning(request, "The main page has already been created. Creating a new one is prohibited.")
            return redirect('admin_panel:main_page_list')
        return super().dispatch(request, *args, **kwargs)

class MainPageUpdateView(SuccessMessageMixin, generic.UpdateView):
    model = MainPage
    form_class = MainPageForm
    template_name = "main/main_page_form.html"
    success_url = reverse_lazy("admin_panel:main_page_list")
    success_message = "The main page has been updated successfully"

class MainPageDeleteView(generic.DeleteView):
    model = MainPage
    template_name = "main/main_page_confirm_delete.html"
    success_url = reverse_lazy("admin_panel:main_page_list")

admin_panel/views/seo.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from admin_panel.forms.seo import SeoForm
from admin_panel.models import SeoBlock
from django.contrib.messages.views import SuccessMessageMixin


class SeoBlockListView(generic.ListView):
    model = SeoBlock
    template_name = "seo/seo_list.html"
    context_object_name = "seo_list"


class SeoBlockCreateView(generic.CreateView):
    model = SeoBlock
    template_name = "seo/seo_form.html"
    form_class = SeoForm
    success_url = reverse_lazy("admin_panel:seo_block_list")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "SEO блок успішно створено!")
        return response


class SeoBlockUpdateView(SuccessMessageMixin, generic.UpdateView):
    model = SeoBlock
    form_class = SeoForm
    template_name = "seo/seo_form.html"
    success_url = reverse_lazy("admin_panel:seo_block_list")
    success_message = "The main page has been updated successfully"


class SeoBlockDeleteView(generic.DeleteView):
    model = SeoBlock
    template_name = "seo/seo_confirm_delete.html"
    success_url = reverse_lazy("admin_panel:seo_block_list")

main/views.py
from django.shortcuts import render

# Create your views here.

admin_panel/templates/main/main_page_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container d-flex justify-content-center align-items-center min-vh-100" style="margin-top: 10px">
    <div class="card shadow-lg border-0 p-4" style="max-width: 600px; width: 100%; border-radius: 20px;">
      <div class="card-body text-center">

        <h1 class="mb-4 text-danger fw-bold">⚠ Delete Main Page</h1>

        <p class="fs-5">
          Are you sure you want to delete seo:
          <strong class="text-info">{{ object.title }}</strong>?
        </p>

        <!-- Відступ зверху -->
        <form action="" method="POST" class="mt-5">
          {% csrf_token %}
          <!-- Відступи між кнопками -->
          <div class="d-flex" style="justify-content: space-around; flex-wrap: wrap">
            <input type="submit" value="✅ Yes, delete" class="btn btn-danger px-4 py-2 fw-semibold me-3">
            <a href="{% url 'admin_panel:main_page_list' %}" class="btn btn-secondary px-4 py-2 fw-semibold">
              ❌ Cancel
            </a>
          </div>
        </form>

      </div>
    </div>
  </div>



{% endblock %}

admin_panel/templates/main/main_page_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load widget_tweaks %}


{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
  {% endif %}
  <div class="container mt-5">
    <div class="d-flex align-items-center justify-content-between mb-4">
      <h1 class="mb-0">{{ object|yesno:"Update,Create" }} page</h1>

      <!-- Кастомний toggle -->

    </div>

    <form method="POST">
      {% csrf_token %}
      <div class="form-check form-switch mb-0" style="float: right">
        {{ form.is_active|add_class:"form-check-input custom-toggle" }}
      </div>
      <div class="form-group">
        <label for="id_title">Title</label>
        {{ form.title }}
      </div>

      <div class="form-group">
        <label for="id_published_date">Date published</label>
        {{ form.published_date }}
      </div>

      <div class="form-group row mb-3">
        <div class="col">
          <label for="id_phone_primary">Primary phone</label>
          {{ form.phone_primary|add_class:"form-control" }}
          {% if form.phone_primary.errors %}
            <ul class="errors">
              {% for error in form.phone_primary.errors %}
                <li style="color: red">{{ error }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>

        <div class="col">
          <label for="id_phone_secondary">Secondary phone</label>
          {{ form.phone_secondary|add_class:"form-control" }}
          {% if form.phone_secondary.errors %}
            <ul class="errors">
              {% for error in form.phone_secondary.errors %}
                <li style="color: red">{{ error }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>
      </div>


      <div class="form-group">
        <label for="id_seo_description">SEO description</label>
        {{ form.seo_description }}
      </div>
      <div style="display: flex; flex-wrap: wrap; align-items: center;">
        <div class="form-group">
          <label for="id_seo">Choose Seo</label>
          {{ form.seo|add_class:"form-select" }}

        </div>
        <div>

          <a href="{% url 'admin_panel:seo_block_create' %}" target="_blank">
            <i class='bx bx-plus bx-sm'></i>
          </a>
        </div>
      </div>
      <button type="submit" class="btn btn-primary mt-3">Зберегти</button>
      <a href="{% url 'admin_panel:main_page_list' %}" class="btn btn-secondary mt-3">Відмінити</a>
    </form>
  </div>

  <style>
      /* Кастомний toggle */
      .custom-toggle {
          width: 50px;
          height: 25px;
          cursor: pointer;
          position: relative;
          -webkit-appearance: none;
          background-color: #ddd;
          border-radius: 25px;
          outline: none;
          transition: background 0.3s;
      }

      .custom-toggle:checked {
          background-color: #3C91E6; /* синій активний */
      }

      .custom-toggle::before {
          content: '';
          position: absolute;
          top: 2px;
          left: 2px;
          width: 21px;
          height: 21px;
          border-radius: 50%;
          background: white;
          transition: 0.3s;
      }

      .custom-toggle:checked::before {
          transform: translateX(25px);
      }

      .form-select {
          border-radius: 0.5rem;
          padding: 0.5rem 1rem;
          border: 1px solid #ced4da;
          transition: all 0.3s;
      }

      .form-select:focus {
          border-color: #3C91E6;
          box-shadow: 0 0 0 0.2rem rgba(60, 145, 230, 0.25);
          outline: none;
      }

      .form-select option {
          padding: 0.5rem;
      }
  </style>




{% endblock %}

admin_panel/templates/main/main_page_list.html
{% extends "base.html" %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
  {% endif %}
  <div class="table-container">
    <h1>Main page</h1>
    <div class="add-btn-container">
      <a href="{% url 'admin_panel:main_page_create' %}" class="btn-add">Add page</a>
    </div>

    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Date Published</th>
        <th scope="col">Status</th>
        <th scope="col">Action</th>
      </tr>
      </thead>
      <tbody>
      {% for main in main_page_list %}
        <tr>
          <th scope="row">{{ main.title }}</th>
          <td>{{ main.published_date }}</td>
          <td>{{ main.is_active }}</td>
          <td>
            <a href="{% url 'admin_panel:main_page_update' main.id %}" class="btn btn-outline-warning">Редагувати</a>
            <a href="{% url 'admin_panel:main_page_delete' main.id %}" class="btn btn-outline-danger">Видалити</a>
          </td>
        </tr>
      {% empty %}

        <tr>
          <td colspan="5">No pages available</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}